/// The Base class is imported as Window from widgets.slint.
import { AppWindow } from "../ui/widgets.slint";

import { TabWidget, Slider, HorizontalBox, Switch } from "std-widgets.slint";

import { SensorStatus } from "../ui/datatypes.slint";

export { SensorStatus }


export component MainWindow inherits AppWindow {
    //width: 320px;
    //height: 240px;

    VerticalLayout {
        Text { text: "Welcome to the Slint Workshop"; horizontal-alignment: center; }
        Text { text: "Screen resolution: \{root.width*1phx/1px/1phx} x \{root.height*1phx/1px/1phx}"; horizontal-alignment: center; }

        Switch {
            text: "This is a switch";
        }
    }

}
