/// The Base class is imported as Window from widgets.slint.
import { AppWindow } from "../ui/widgets.slint";

import { Switch, TabWidget, AboutSlint } from "std-widgets.slint";
import { WifiNetworkPage } from "../ui/pages.slint";

import { WifiNetwork } from "../ui/viewmodel.slint";

export component MainWindow inherits AppWindow {
    in property <[WifiNetwork]> wifi_network_model <=> wifi.model;

    callback wifi_refresh;
    
    public function invoke_wifi_refresh() {
        self.wifi_refresh();
    }

    TabWidget {
        Tab {
            title: @tr("Wifi");

            wifi := WifiNetworkPage {
                refresh => {
                    root.wifi_refresh();
                }
            }
        }

        Tab {
            title: @tr("About");

            AboutSlint { }
        }
    }
}
