[workspace]
members = [
    "winit",
    "common",
    #    "wasm"
    #    "android"
]

exclude = ["esp32", "ui"]

[workspace.package]
name = "slint-workshop"
version = "0.2.0"
authors = ["Michael Winkelmann <michael@winkelmann.site>"]
edition = "2021"
resolver = "2"
rust-version = "1.80"
