[workspace]
members = ["winit", "model"]

exclude = ["esp32-no_std", "esp32-std", "ui", "wasm", "android"]

[workspace.package]
version = "0.2.0"
authors = ["Michael Winkelmann <michael@winkelmann.site>"]
edition = "2024"
rust-version = "1.85"
