# Wokwi Configuration File
# Reference: https://docs.wokwi.com/vscode/project-config
[wokwi]
version = 1
firmware = 'target/xtensa-esp32s3-none-elf/release/slint-workshop-esp-m5stack-cores3'
elf = 'target/xtensa-esp32s3-none-elf/release/slint-workshop-esp-m5stack-cores3'
