import { Switch, TabWidget, AboutSlint } from "std-widgets.slint";
import { WifiNetworkPage } from "pages.slint";

import { WifiNetwork } from "viewmodel.slint";

export component MainWindow inherits Window {
    in property <[WifiNetwork]> wifi_network_model;

    callback wifi_refresh;
    public function invoke_wifi_refresh() {
        self.wifi_refresh();
    }

    TabWidget {

        Tab {
            title: @tr("Wifi");

            wifi := WifiNetworkPage {
                model: root.wifi_network_model;
                refresh => {
                    root.wifi_refresh();
                }
            }
        }

        Tab {
            title: @tr("About");

            AboutSlint { }
        }
    }
}
