import { Switch, TabWidget, AboutSlint } from "std-widgets.slint";
import { WifiNetworkPage, TemperaturePage } from "pages.slint";

import { WifiNetwork, WeatherRecord } from "viewmodel.slint";

export component MainWindow inherits Window {
    in property <[WifiNetwork]> wifi_network_model;
    in property <WeatherRecord> weather-record;

    callback wifi_refresh;
    public function invoke_wifi_refresh() {
        self.wifi_refresh();
    }

    TabWidget {
        Tab {
            title: "Temperature";

            TemperaturePage {
                temperature-celsius: weather-record.temperature_celsius;
                humidity-percent: weather-record.humidity_percent;
            }
        }

        Tab {
            title: @tr("Wifi");

            wifi := WifiNetworkPage {
                model: root.wifi_network_model;
                refresh => {
                    root.wifi_refresh();
                }
            }
        }

        Tab {
            title: @tr("About");

            AboutSlint { }
        }
    }
}
