/// This slint file contains all definitions for styles used in the UI.

/// Style metrics for the application
/// 
/// These metrics are used to define the sizes of various UI elements in the application.
export global StyleMetrics {
    out property <length> padding: 9px;

    out property <length> title-height: 30px;
    out property <length> status-height: 24px;

    out property <length> indicator-bar-width: 40px;
}
