# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: MIT

# Settings for M5Stack CoreS3 board

[env]
ESP_LOG = "INFO"
ESP_HAL_CONFIG_PSRAM_MODE = "quad"

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor --partition-table=partitions.csv --flash-size=16mb"
rustflags = ["-C", "link-arg=-Wl,-Tlinkall.x"]

[build]
target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["core", "alloc"]
