import { TabWidget } from "std-widgets.slint";

import { WeatherRecord, SensorStatus } from "logic.slint";

import { AppWindow as Window } from "widgets.slint";
import { TemperaturePage, ScreenBrightnessPage } from "pages.slint";


export global ViewModel {
    in property <SensorStatus> sensor-status;
    in property <WeatherRecord> current;

    pure callback screen-brightness-changed(float);
}


export component AppWindow inherits Window {
    status-bar-text: ViewModel.current.timestamp;

    TabWidget {
        Tab {
            title: "Temperature";

            TemperaturePage {
                temperature-celsius: ViewModel.current.temperature_celsius;
                humidity-percent: ViewModel.current.humidity_percent;
            }
        }

        Tab {
            title: "Brightness";

            ScreenBrightnessPage {
                screen-brightness-changed => { ViewModel.screen-brightness-changed(self.screen-brightness); }
            }
        }
    }
}
