import { TabWidget } from "std-widgets.slint";

import { AppWindow as Window } from "widgets.slint";
import { ForecastPage, TemperaturePage, RecordingPage } from "pages.slint";

import { WeatherRecord } from "datatypes.slint";

export global ViewModel {
    in property <WeatherRecord> current;
    in property <[WeatherRecord]> records;
}

export component AppWindow inherits Window {
    status-bar-text: ViewModel.current.timestamp;

    TabWidget {
        Tab {
            title: "Temperature";

            TemperaturePage {
                temperature-celsius: ViewModel.current.temperature_celsius;
                humidity-percent: ViewModel.current.humidity_percent;
            }
        }

        Tab {
            title: "Recording";

            RecordingPage {
                records: ViewModel.records;
            }
        }

        Tab {
            title: "Forecast";

            ForecastPage {}
        }
    }
}
