import { Button, VerticalBox, HorizontalBox, TabWidget, Slider } from "std-widgets.slint";
import { Indicator, TitleBar, StatusBar, AppStyleMetrics, HumidityBar, TemperatureBar } from "widgets.slint";

import { * } from "logic.slint";

export component AppWindow inherits Window {
    in-out property<int> counter: 42;
    callback slider-changed(float);

    width: 320px;
    height: 240px;

    VerticalLayout {
        TitleBar {
            text: "Slint Weather Station";
        }
        TabWidget {
            Tab {
                Rectangle {
                    background: #ffffff;

                    HorizontalBox {
                        TemperatureBar {
                            value: ViewModel.current.temperature-celsius;
                        }
                        HumidityBar {
                            value: ViewModel.current.humidity-percent;
                        }
                    }
                }
            }
            Tab {
                Slider {
                    width: 200px;
                    changed => { root.slider-changed(self.value); }
                }
            }
        }
        StatusBar {
            text: ViewModel.current.timestamp;
        }
    }
}