
import { Button, VerticalBox, HorizontalBox, TabWidget, Slider } from "std-widgets.slint";

import { ViewModel } from "logic.slint";

import { StatusBar, TitleBar, TemperatureBar, HumidityBar } from "widgets.slint";

component Page inherits Rectangle {
    background: #ffffff;
}

export component TemperaturePage inherits Page {
    HorizontalBox {
        TemperatureBar {
            value: ViewModel.current.temperature-celsius;
        }
        HumidityBar {
            value: ViewModel.current.humidity-percent;
        }
    }
}

export component ForecastPage inherits Page {

}

export component RecordingPage inherits Page {
}

export component ScreenBrightnessPage inherits Page {
    property screen-brightness <=> slider.value;
    callback screen-brightness-changed(float);
    
    padding: 4px;

    slider := Slider {
        width: parent.width * 80%;
        height: parent.height;

        minimum: 10; // Minimum brightness is 10%, to avoid black screen.
        maximum: 100;
        value: 100;
        changed => { root.screen-brightness-changed(self.value); }
    }
}
