import { Palette } from "std-widgets.slint";

/// Style metrics for the application
/// 
/// These metrics are used to define the sizes of various UI elements in the application.
export global StyleMetrics {
    out property <length> padding: 9px;

    out property <length> title-height: 30px;
    out property <length> status-height: 24px;

    out property <length> indicator-bar-width: 40px;
}

// export global AppFonts { /* */ }

// export global Images { /*  */ }

/// The color palette used in the application, re-exported from std-widgets.slint
/// See https://docs.slint.dev/latest/docs/slint/src/language/builtins/globals#palette for more information.
export { Palette }

// We could also define a custom Palette here, but we'll use the default one for now.
// export global Palette {
//     out property <brush> background: #ffffff;
//     out property <brush> alternate-background: #f0f0f0;
//     out property <brush> text: #000000;
//     out property <brush> accent: #0078d4;
// }


